name: pigo
version: '1.4.5'
summary: Pure Go face detection library
description: |
  Key features:
   - Does not require OpenCV or any 3rd party modules to be installed
   - High processing speed
   - There is no need for image preprocessing prior detection
   - There is no need for the computation of integral images, image pyramid, HOG pyramid or any other similar data structure
   - The face detection is based on pixel intensity comparison encoded in the binary file tree structure
   - Fast detection of in-plane rotated faces
   - Pupils/eyes detection
   - Facial landmark points detection
   - WASM (Webassembly) support
grade: stable
confinement: strict
base: core18
parts:
  pigo:
    plugin: nil
    source: .
    build-snaps: [go]
    override-build: |
      export GOBIN=$SNAPCRAFT_PART_INSTALL/bin
      export GO111MODULE=on
      export CGO_ENABLED=0
      go build cmd/pigo/main.go

    filesets:
      exclude-wasm-files:
        - -wasm